<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <RootNamespace>IdxDb.DemoApp</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <_ContentIncludedByDefault Remove="wwwroot\js\idb.js" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\library\IdxDb\IdxDb.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MudBlazor" />
  </ItemGroup>

</Project>