<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <RootNamespace>IdxDb.DemoApp</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <_ContentIncludedByDefault Remove="wwwroot\js\idb.js" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\library\IdxDb\IdxDb.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" PrivateAssets="all" />
    <PackageReference Include="MudBlazor" />
  </ItemGroup>

</Project>